### ISSUE TITLE
XCI update

### ISSUE THREAD

**Issue by rxpmaia** [Ishan09811/pine#13]
Does not recognize XCI update and DLC.

**Comment by Ishan09811** [comment]
Update or dlc support is not implemented yet

**Comment by rxpmaia** [comment]
Ok

Em sex., 26 de jul. de 2024, 00:50, Ishan09811 ***@***.***>
escreveu:

**Comment by Ishan09811** [comment]
now it is implemented by #62 but will only for nsp games
